version: '3.8'

services:
  raspi-screen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raspi-screen
    restart: unless-stopped
    ports:
      - "80:80"  # Flask server
      - "5001:5001"  # Activation service
    volumes:
      - ./logs:/app/logs  # Log directory
      - ./static:/app/static  # Static files
      - ./config:/app/config  # Configurations (e.g., hostapd, dnsmasq)
    environment:
      - FLASK_APP=server/app.py
      - FLASK_ENV=production
      - SERVER_PORT=5001
      - SERVER_URL=http://192.168.0.99:5001
      - TZ=Europe/Paris
      - PYTHONUNBUFFERED=1
    privileged: true  # Required for network management
    networks:
      - raspi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  # Give enough time for the service to start

networks:
  raspi-network:
    driver: bridge
